SET IDENTITY_INSERT [dbo].[Books] ON
INSERT INTO [dbo].[Books] ([Id], [Name], [Genre], [OriginalPublisher], [YearFirst]) VALUES (1, N'It', 2048, 8, 1985)
INSERT INTO [dbo].[Books] ([Id], [Name], [Genre], [OriginalPublisher], [YearFirst]) VALUES (2, N'Carrie', 32, 5, 1974)
INSERT INTO [dbo].[Books] ([Id], [Name], [Genre], [OriginalPublisher], [YearFirst]) VALUES (3, N'UNder The Dome', 2048, 2, 2013)
INSERT INTO [dbo].[Books] ([Id], [Name], [Genre], [OriginalPublisher], [YearFirst]) VALUES (4, N'The Gilded Age: A Tale of Today', 10240, 1, 1873)
INSERT INTO [dbo].[Books] ([Id], [Name], [Genre], [OriginalPublisher], [YearFirst]) VALUES (5, N'The Prince and the Pauper', 18, 2, 1881)
INSERT INTO [dbo].[Books] ([Id], [Name], [Genre], [OriginalPublisher], [YearFirst]) VALUES (6, N'A Connecticut Yankee in King Arthur''s Court', 8210, 2, 1889)
INSERT INTO [dbo].[Books] ([Id], [Name], [Genre], [OriginalPublisher], [YearFirst]) VALUES (7, N'Sense and Sensibility ', 8, 3, 1811)
INSERT INTO [dbo].[Books] ([Id], [Name], [Genre], [OriginalPublisher], [YearFirst]) VALUES (9, N'Emma', 8, 3, 1815)
INSERT INTO [dbo].[Books] ([Id], [Name], [Genre], [OriginalPublisher], [YearFirst]) VALUES (17, N'the Lion the Withc and the wardrobe', 2112, 9, 1950)
INSERT INTO [dbo].[Books] ([Id], [Name], [Genre], [OriginalPublisher], [YearFirst]) VALUES (19, N'The Magicians Nephew', 2112, 9, 1955)
INSERT INTO [dbo].[Books] ([Id], [Name], [Genre], [OriginalPublisher], [YearFirst]) VALUES (20, N'The Two Towers', 2048, 10, 1954)
INSERT INTO [dbo].[Books] ([Id], [Name], [Genre], [OriginalPublisher], [YearFirst]) VALUES (21, N'The Adventures of Tom Bombadil', 2048, 10, 1955)
INSERT INTO [dbo].[Books] ([Id], [Name], [Genre], [OriginalPublisher], [YearFirst]) VALUES (22, N'Bleak House', 3, 11, 1853)
INSERT INTO [dbo].[Books] ([Id], [Name], [Genre], [OriginalPublisher], [YearFirst]) VALUES (26, N'Strange Case of Dr Jekyll and Mr Hyde', 8192, 12, 1886)
SET IDENTITY_INSERT [dbo].[Books] OFF
