INSERT INTO [dbo].[Genres] ([Id], [GenreName]) VALUES (0, N'Unknown')
INSERT INTO [dbo].[Genres] ([Id], [GenreName]) VALUES (1, N'Saitre')
INSERT INTO [dbo].[Genres] ([Id], [GenreName]) VALUES (2, N'Drama')
INSERT INTO [dbo].[Genres] ([Id], [GenreName]) VALUES (4, N'Action and Adventure')
INSERT INTO [dbo].[Genres] ([Id], [GenreName]) VALUES (8, N'Romance')
INSERT INTO [dbo].[Genres] ([Id], [GenreName]) VALUES (16, N'Mystery')
INSERT INTO [dbo].[Genres] ([Id], [GenreName]) VALUES (32, N'Horror')
INSERT INTO [dbo].[Genres] ([Id], [GenreName]) VALUES (64, N'Self help')
INSERT INTO [dbo].[Genres] ([Id], [GenreName]) VALUES (128, N'Travel')
INSERT INTO [dbo].[Genres] ([Id], [GenreName]) VALUES (256, N'Science')
INSERT INTO [dbo].[Genres] ([Id], [GenreName]) VALUES (512, N'History')
INSERT INTO [dbo].[Genres] ([Id], [GenreName]) VALUES (1024, N'Poetry')
INSERT INTO [dbo].[Genres] ([Id], [GenreName]) VALUES (2048, N'Fantasy')
INSERT INTO [dbo].[Genres] ([Id], [GenreName]) VALUES (4096, N'Journals')
INSERT INTO [dbo].[Genres] ([Id], [GenreName]) VALUES (8192, N'Science Fiction')
